// Generated from the official Minecraft 1.21.11 server data.
export const MINECRAFT_DAMAGE_TYPE_IDS_1_21_11 = new Set<string>([
  "minecraft:arrow", "minecraft:bad_respawn_point", "minecraft:cactus", "minecraft:campfire", "minecraft:cramming", "minecraft:dragon_breath", "minecraft:drown", "minecraft:dry_out",
  "minecraft:ender_pearl", "minecraft:explosion", "minecraft:fall", "minecraft:falling_anvil", "minecraft:falling_block", "minecraft:falling_stalactite", "minecraft:fireball", "minecraft:fireworks",
  "minecraft:fly_into_wall", "minecraft:freeze", "minecraft:generic", "minecraft:generic_kill", "minecraft:hot_floor", "minecraft:in_fire", "minecraft:in_wall", "minecraft:indirect_magic",
  "minecraft:lava", "minecraft:lightning_bolt", "minecraft:mace_smash", "minecraft:magic", "minecraft:mob_attack", "minecraft:mob_attack_no_aggro", "minecraft:mob_projectile", "minecraft:on_fire",
  "minecraft:out_of_world", "minecraft:outside_border", "minecraft:player_attack", "minecraft:player_explosion", "minecraft:sonic_boom", "minecraft:spear", "minecraft:spit", "minecraft:stalagmite",
  "minecraft:starve", "minecraft:sting", "minecraft:sweet_berry_bush", "minecraft:thorns", "minecraft:thrown", "minecraft:trident", "minecraft:unattributed_fireball", "minecraft:wind_charge",
  "minecraft:wither", "minecraft:wither_skull",
]);

export const MINECRAFT_DAMAGE_TYPE_TAG_VALUES_1_21_11: Readonly<Record<string, readonly string[]>> = {
  "minecraft:always_hurts_ender_dragons": ["minecraft:bad_respawn_point","minecraft:explosion","minecraft:fireworks","minecraft:player_explosion"],
  "minecraft:always_kills_armor_stands": ["minecraft:arrow","minecraft:fireball","minecraft:trident","minecraft:wind_charge","minecraft:wither_skull"],
  "minecraft:always_most_significant_fall": ["minecraft:out_of_world"],
  "minecraft:always_triggers_silverfish": ["minecraft:magic"],
  "minecraft:avoids_guardian_thorns": ["minecraft:bad_respawn_point","minecraft:explosion","minecraft:fireworks","minecraft:magic","minecraft:player_explosion","minecraft:thorns"],
  "minecraft:burn_from_stepping": ["minecraft:campfire","minecraft:hot_floor"],
  "minecraft:burns_armor_stands": ["minecraft:on_fire"],
  "minecraft:bypasses_armor": ["minecraft:cramming","minecraft:dragon_breath","minecraft:drown","minecraft:ender_pearl","minecraft:fall","minecraft:fly_into_wall","minecraft:freeze","minecraft:generic","minecraft:generic_kill","minecraft:in_wall","minecraft:indirect_magic","minecraft:magic","minecraft:on_fire","minecraft:out_of_world","minecraft:outside_border","minecraft:sonic_boom","minecraft:stalagmite","minecraft:starve","minecraft:wither"],
  "minecraft:bypasses_effects": ["minecraft:starve"],
  "minecraft:bypasses_enchantments": ["minecraft:sonic_boom"],
  "minecraft:bypasses_invulnerability": ["minecraft:generic_kill","minecraft:out_of_world"],
  "minecraft:bypasses_resistance": ["minecraft:generic_kill","minecraft:out_of_world"],
  "minecraft:bypasses_shield": ["minecraft:cactus","minecraft:campfire","minecraft:cramming","minecraft:dragon_breath","minecraft:drown","minecraft:dry_out","minecraft:ender_pearl","minecraft:fall","minecraft:falling_anvil","minecraft:falling_stalactite","minecraft:fly_into_wall","minecraft:freeze","minecraft:generic","minecraft:generic_kill","minecraft:hot_floor","minecraft:in_fire","minecraft:in_wall","minecraft:indirect_magic","minecraft:lava","minecraft:lightning_bolt","minecraft:magic","minecraft:on_fire","minecraft:out_of_world","minecraft:outside_border","minecraft:sonic_boom","minecraft:stalagmite","minecraft:starve","minecraft:sweet_berry_bush","minecraft:wither"],
  "minecraft:bypasses_wolf_armor": ["minecraft:cramming","minecraft:drown","minecraft:dry_out","minecraft:freeze","minecraft:generic_kill","minecraft:in_wall","minecraft:indirect_magic","minecraft:magic","minecraft:out_of_world","minecraft:outside_border","minecraft:starve","minecraft:thorns","minecraft:wither"],
  "minecraft:can_break_armor_stand": ["minecraft:mace_smash","minecraft:player_attack","minecraft:player_explosion","minecraft:spear"],
  "minecraft:damages_helmet": ["minecraft:falling_anvil","minecraft:falling_block","minecraft:falling_stalactite"],
  "minecraft:ignites_armor_stands": ["minecraft:campfire","minecraft:in_fire"],
  "minecraft:is_drowning": ["minecraft:drown"],
  "minecraft:is_explosion": ["minecraft:bad_respawn_point","minecraft:explosion","minecraft:fireworks","minecraft:player_explosion"],
  "minecraft:is_fall": ["minecraft:ender_pearl","minecraft:fall","minecraft:stalagmite"],
  "minecraft:is_fire": ["minecraft:campfire","minecraft:fireball","minecraft:hot_floor","minecraft:in_fire","minecraft:lava","minecraft:on_fire","minecraft:unattributed_fireball"],
  "minecraft:is_freezing": ["minecraft:freeze"],
  "minecraft:is_lightning": ["minecraft:lightning_bolt"],
  "minecraft:is_player_attack": ["minecraft:mace_smash","minecraft:player_attack","minecraft:spear"],
  "minecraft:is_projectile": ["minecraft:arrow","minecraft:fireball","minecraft:mob_projectile","minecraft:thrown","minecraft:trident","minecraft:unattributed_fireball","minecraft:wind_charge","minecraft:wither_skull"],
  "minecraft:mace_smash": ["minecraft:mace_smash"],
  "minecraft:no_anger": ["minecraft:mob_attack_no_aggro"],
  "minecraft:no_impact": ["minecraft:drown"],
  "minecraft:no_knockback": ["minecraft:bad_respawn_point","minecraft:cactus","minecraft:campfire","minecraft:cramming","minecraft:dragon_breath","minecraft:drown","minecraft:dry_out","minecraft:ender_pearl","minecraft:explosion","minecraft:fall","minecraft:fly_into_wall","minecraft:freeze","minecraft:generic","minecraft:generic_kill","minecraft:hot_floor","minecraft:in_fire","minecraft:in_wall","minecraft:lava","minecraft:lightning_bolt","minecraft:magic","minecraft:on_fire","minecraft:out_of_world","minecraft:outside_border","minecraft:player_explosion","minecraft:spear","minecraft:stalagmite","minecraft:starve","minecraft:sweet_berry_bush","minecraft:wither"],
  "minecraft:panic_causes": ["minecraft:arrow","minecraft:cactus","minecraft:dragon_breath","minecraft:explosion","minecraft:fireball","minecraft:fireworks","minecraft:freeze","minecraft:hot_floor","minecraft:in_fire","minecraft:indirect_magic","minecraft:lava","minecraft:lightning_bolt","minecraft:mace_smash","minecraft:magic","minecraft:mob_attack","minecraft:mob_projectile","minecraft:on_fire","minecraft:player_attack","minecraft:player_explosion","minecraft:sonic_boom","minecraft:spear","minecraft:sting","minecraft:thrown","minecraft:trident","minecraft:unattributed_fireball","minecraft:wind_charge","minecraft:wither","minecraft:wither_skull"],
  "minecraft:panic_environmental_causes": ["minecraft:cactus","minecraft:freeze","minecraft:hot_floor","minecraft:in_fire","minecraft:lava","minecraft:lightning_bolt","minecraft:on_fire"],
  "minecraft:witch_resistant_to": ["minecraft:indirect_magic","minecraft:magic","minecraft:sonic_boom","minecraft:thorns"],
  "minecraft:wither_immune_to": ["minecraft:drown"],
};
