import type { JsonObject } from "./types.js";

// Generated from the official Minecraft 1.21.11 items report.
// Nexo inherits missing consumable builder fields from the base ItemStack.
export const MINECRAFT_CONSUMABLE_COMPONENTS_1_21_11: Readonly<Record<string, JsonObject>> = {
  "minecraft:apple": {},
  "minecraft:baked_potato": {},
  "minecraft:beef": {},
  "minecraft:beetroot": {},
  "minecraft:beetroot_soup": {},
  "minecraft:bread": {},
  "minecraft:carrot": {},
  "minecraft:chicken": {"on_consume_effects":[{"type":"minecraft:apply_effects","effects":[{"duration":600,"id":"minecraft:hunger","show_icon":true}],"probability":0.3}]},
  "minecraft:chorus_fruit": {"on_consume_effects":[{"type":"minecraft:teleport_randomly"}]},
  "minecraft:cod": {},
  "minecraft:cooked_beef": {},
  "minecraft:cooked_chicken": {},
  "minecraft:cooked_cod": {},
  "minecraft:cooked_mutton": {},
  "minecraft:cooked_porkchop": {},
  "minecraft:cooked_rabbit": {},
  "minecraft:cooked_salmon": {},
  "minecraft:cookie": {},
  "minecraft:dried_kelp": {"consume_seconds":0.8},
  "minecraft:enchanted_golden_apple": {"on_consume_effects":[{"type":"minecraft:apply_effects","effects":[{"amplifier":1,"duration":400,"id":"minecraft:regeneration","show_icon":true},{"duration":6000,"id":"minecraft:resistance","show_icon":true},{"duration":6000,"id":"minecraft:fire_resistance","show_icon":true},{"amplifier":3,"duration":2400,"id":"minecraft:absorption","show_icon":true}]}]},
  "minecraft:glow_berries": {},
  "minecraft:golden_apple": {"on_consume_effects":[{"type":"minecraft:apply_effects","effects":[{"amplifier":1,"duration":100,"id":"minecraft:regeneration","show_icon":true},{"duration":2400,"id":"minecraft:absorption","show_icon":true}]}]},
  "minecraft:golden_carrot": {},
  "minecraft:honey_bottle": {"animation":"drink","consume_seconds":2,"has_consume_particles":false,"on_consume_effects":[{"type":"minecraft:remove_effects","effects":"minecraft:poison"}],"sound":"minecraft:item.honey_bottle.drink"},
  "minecraft:melon_slice": {},
  "minecraft:milk_bucket": {"animation":"drink","has_consume_particles":false,"on_consume_effects":[{"type":"minecraft:clear_all_effects"}],"sound":"minecraft:entity.generic.drink"},
  "minecraft:mushroom_stew": {},
  "minecraft:mutton": {},
  "minecraft:ominous_bottle": {"animation":"drink","has_consume_particles":false,"on_consume_effects":[{"type":"minecraft:play_sound","sound":"minecraft:item.ominous_bottle.dispose"}],"sound":"minecraft:entity.generic.drink"},
  "minecraft:poisonous_potato": {"on_consume_effects":[{"type":"minecraft:apply_effects","effects":[{"duration":100,"id":"minecraft:poison","show_icon":true}],"probability":0.6}]},
  "minecraft:porkchop": {},
  "minecraft:potato": {},
  "minecraft:potion": {"animation":"drink","has_consume_particles":false,"sound":"minecraft:entity.generic.drink"},
  "minecraft:pufferfish": {"on_consume_effects":[{"type":"minecraft:apply_effects","effects":[{"amplifier":1,"duration":1200,"id":"minecraft:poison","show_icon":true},{"amplifier":2,"duration":300,"id":"minecraft:hunger","show_icon":true},{"duration":300,"id":"minecraft:nausea","show_icon":true}]}]},
  "minecraft:pumpkin_pie": {},
  "minecraft:rabbit": {},
  "minecraft:rabbit_stew": {},
  "minecraft:rotten_flesh": {"on_consume_effects":[{"type":"minecraft:apply_effects","effects":[{"duration":600,"id":"minecraft:hunger","show_icon":true}],"probability":0.8}]},
  "minecraft:salmon": {},
  "minecraft:spider_eye": {"on_consume_effects":[{"type":"minecraft:apply_effects","effects":[{"duration":100,"id":"minecraft:poison","show_icon":true}]}]},
  "minecraft:suspicious_stew": {},
  "minecraft:sweet_berries": {},
  "minecraft:tropical_fish": {},
};
