//! Official Minecraft 1.21.11 blocks report: property names per block.
//!
//! Generated by work/gen-data.mts from legacy/src/minecraft-block-states-1.21.11.ts.
//! Do not edit by hand; re-run the generator after data changes.

use std::collections::HashMap;
use std::sync::LazyLock;




static BLOCK_STATE_PROPERTIES_JSON: &str = r##"{
 "minecraft:acacia_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:acacia_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:acacia_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:acacia_fence_gate": [
  "facing",
  "in_wall",
  "open",
  "powered"
 ],
 "minecraft:acacia_hanging_sign": [
  "attached",
  "rotation",
  "waterlogged"
 ],
 "minecraft:acacia_leaves": [
  "distance",
  "persistent",
  "waterlogged"
 ],
 "minecraft:acacia_log": [
  "axis"
 ],
 "minecraft:acacia_pressure_plate": [
  "powered"
 ],
 "minecraft:acacia_sapling": [
  "stage"
 ],
 "minecraft:acacia_shelf": [
  "facing",
  "powered",
  "side_chain",
  "waterlogged"
 ],
 "minecraft:acacia_sign": [
  "rotation",
  "waterlogged"
 ],
 "minecraft:acacia_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:acacia_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:acacia_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:acacia_wall_hanging_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:acacia_wall_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:acacia_wood": [
  "axis"
 ],
 "minecraft:activator_rail": [
  "powered",
  "shape",
  "waterlogged"
 ],
 "minecraft:amethyst_cluster": [
  "facing",
  "waterlogged"
 ],
 "minecraft:andesite_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:andesite_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:andesite_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:anvil": [
  "facing"
 ],
 "minecraft:attached_melon_stem": [
  "facing"
 ],
 "minecraft:attached_pumpkin_stem": [
  "facing"
 ],
 "minecraft:azalea_leaves": [
  "distance",
  "persistent",
  "waterlogged"
 ],
 "minecraft:bamboo": [
  "age",
  "leaves",
  "stage"
 ],
 "minecraft:bamboo_block": [
  "axis"
 ],
 "minecraft:bamboo_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:bamboo_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:bamboo_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:bamboo_fence_gate": [
  "facing",
  "in_wall",
  "open",
  "powered"
 ],
 "minecraft:bamboo_hanging_sign": [
  "attached",
  "rotation",
  "waterlogged"
 ],
 "minecraft:bamboo_mosaic_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:bamboo_mosaic_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:bamboo_pressure_plate": [
  "powered"
 ],
 "minecraft:bamboo_shelf": [
  "facing",
  "powered",
  "side_chain",
  "waterlogged"
 ],
 "minecraft:bamboo_sign": [
  "rotation",
  "waterlogged"
 ],
 "minecraft:bamboo_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:bamboo_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:bamboo_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:bamboo_wall_hanging_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:bamboo_wall_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:barrel": [
  "facing",
  "open"
 ],
 "minecraft:barrier": [
  "waterlogged"
 ],
 "minecraft:basalt": [
  "axis"
 ],
 "minecraft:bee_nest": [
  "facing",
  "honey_level"
 ],
 "minecraft:beehive": [
  "facing",
  "honey_level"
 ],
 "minecraft:beetroots": [
  "age"
 ],
 "minecraft:bell": [
  "attachment",
  "facing",
  "powered"
 ],
 "minecraft:big_dripleaf": [
  "facing",
  "tilt",
  "waterlogged"
 ],
 "minecraft:big_dripleaf_stem": [
  "facing",
  "waterlogged"
 ],
 "minecraft:birch_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:birch_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:birch_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:birch_fence_gate": [
  "facing",
  "in_wall",
  "open",
  "powered"
 ],
 "minecraft:birch_hanging_sign": [
  "attached",
  "rotation",
  "waterlogged"
 ],
 "minecraft:birch_leaves": [
  "distance",
  "persistent",
  "waterlogged"
 ],
 "minecraft:birch_log": [
  "axis"
 ],
 "minecraft:birch_pressure_plate": [
  "powered"
 ],
 "minecraft:birch_sapling": [
  "stage"
 ],
 "minecraft:birch_shelf": [
  "facing",
  "powered",
  "side_chain",
  "waterlogged"
 ],
 "minecraft:birch_sign": [
  "rotation",
  "waterlogged"
 ],
 "minecraft:birch_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:birch_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:birch_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:birch_wall_hanging_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:birch_wall_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:birch_wood": [
  "axis"
 ],
 "minecraft:black_banner": [
  "rotation"
 ],
 "minecraft:black_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:black_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:black_candle_cake": [
  "lit"
 ],
 "minecraft:black_glazed_terracotta": [
  "facing"
 ],
 "minecraft:black_shulker_box": [
  "facing"
 ],
 "minecraft:black_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:black_wall_banner": [
  "facing"
 ],
 "minecraft:blackstone_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:blackstone_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:blackstone_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:blast_furnace": [
  "facing",
  "lit"
 ],
 "minecraft:blue_banner": [
  "rotation"
 ],
 "minecraft:blue_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:blue_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:blue_candle_cake": [
  "lit"
 ],
 "minecraft:blue_glazed_terracotta": [
  "facing"
 ],
 "minecraft:blue_shulker_box": [
  "facing"
 ],
 "minecraft:blue_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:blue_wall_banner": [
  "facing"
 ],
 "minecraft:bone_block": [
  "axis"
 ],
 "minecraft:brain_coral": [
  "waterlogged"
 ],
 "minecraft:brain_coral_fan": [
  "waterlogged"
 ],
 "minecraft:brain_coral_wall_fan": [
  "facing",
  "waterlogged"
 ],
 "minecraft:brewing_stand": [
  "has_bottle_0",
  "has_bottle_1",
  "has_bottle_2"
 ],
 "minecraft:brick_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:brick_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:brick_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:brown_banner": [
  "rotation"
 ],
 "minecraft:brown_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:brown_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:brown_candle_cake": [
  "lit"
 ],
 "minecraft:brown_glazed_terracotta": [
  "facing"
 ],
 "minecraft:brown_mushroom_block": [
  "down",
  "east",
  "north",
  "south",
  "up",
  "west"
 ],
 "minecraft:brown_shulker_box": [
  "facing"
 ],
 "minecraft:brown_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:brown_wall_banner": [
  "facing"
 ],
 "minecraft:bubble_column": [
  "drag"
 ],
 "minecraft:bubble_coral": [
  "waterlogged"
 ],
 "minecraft:bubble_coral_fan": [
  "waterlogged"
 ],
 "minecraft:bubble_coral_wall_fan": [
  "facing",
  "waterlogged"
 ],
 "minecraft:cactus": [
  "age"
 ],
 "minecraft:cake": [
  "bites"
 ],
 "minecraft:calibrated_sculk_sensor": [
  "facing",
  "power",
  "sculk_sensor_phase",
  "waterlogged"
 ],
 "minecraft:campfire": [
  "facing",
  "lit",
  "signal_fire",
  "waterlogged"
 ],
 "minecraft:candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:candle_cake": [
  "lit"
 ],
 "minecraft:carrots": [
  "age"
 ],
 "minecraft:carved_pumpkin": [
  "facing"
 ],
 "minecraft:cave_vines": [
  "age",
  "berries"
 ],
 "minecraft:cave_vines_plant": [
  "berries"
 ],
 "minecraft:chain_command_block": [
  "conditional",
  "facing"
 ],
 "minecraft:cherry_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:cherry_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:cherry_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:cherry_fence_gate": [
  "facing",
  "in_wall",
  "open",
  "powered"
 ],
 "minecraft:cherry_hanging_sign": [
  "attached",
  "rotation",
  "waterlogged"
 ],
 "minecraft:cherry_leaves": [
  "distance",
  "persistent",
  "waterlogged"
 ],
 "minecraft:cherry_log": [
  "axis"
 ],
 "minecraft:cherry_pressure_plate": [
  "powered"
 ],
 "minecraft:cherry_sapling": [
  "stage"
 ],
 "minecraft:cherry_shelf": [
  "facing",
  "powered",
  "side_chain",
  "waterlogged"
 ],
 "minecraft:cherry_sign": [
  "rotation",
  "waterlogged"
 ],
 "minecraft:cherry_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:cherry_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:cherry_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:cherry_wall_hanging_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:cherry_wall_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:cherry_wood": [
  "axis"
 ],
 "minecraft:chest": [
  "facing",
  "type",
  "waterlogged"
 ],
 "minecraft:chipped_anvil": [
  "facing"
 ],
 "minecraft:chiseled_bookshelf": [
  "facing",
  "slot_0_occupied",
  "slot_1_occupied",
  "slot_2_occupied",
  "slot_3_occupied",
  "slot_4_occupied",
  "slot_5_occupied"
 ],
 "minecraft:chorus_flower": [
  "age"
 ],
 "minecraft:chorus_plant": [
  "down",
  "east",
  "north",
  "south",
  "up",
  "west"
 ],
 "minecraft:cobbled_deepslate_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:cobbled_deepslate_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:cobbled_deepslate_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:cobblestone_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:cobblestone_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:cobblestone_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:cocoa": [
  "age",
  "facing"
 ],
 "minecraft:command_block": [
  "conditional",
  "facing"
 ],
 "minecraft:comparator": [
  "facing",
  "mode",
  "powered"
 ],
 "minecraft:composter": [
  "level"
 ],
 "minecraft:conduit": [
  "waterlogged"
 ],
 "minecraft:copper_bars": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:copper_bulb": [
  "lit",
  "powered"
 ],
 "minecraft:copper_chain": [
  "axis",
  "waterlogged"
 ],
 "minecraft:copper_chest": [
  "facing",
  "type",
  "waterlogged"
 ],
 "minecraft:copper_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:copper_golem_statue": [
  "copper_golem_pose",
  "facing",
  "waterlogged"
 ],
 "minecraft:copper_grate": [
  "waterlogged"
 ],
 "minecraft:copper_lantern": [
  "hanging",
  "waterlogged"
 ],
 "minecraft:copper_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:copper_wall_torch": [
  "facing"
 ],
 "minecraft:crafter": [
  "crafting",
  "orientation",
  "triggered"
 ],
 "minecraft:creaking_heart": [
  "axis",
  "creaking_heart_state",
  "natural"
 ],
 "minecraft:creeper_head": [
  "powered",
  "rotation"
 ],
 "minecraft:creeper_wall_head": [
  "facing",
  "powered"
 ],
 "minecraft:crimson_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:crimson_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:crimson_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:crimson_fence_gate": [
  "facing",
  "in_wall",
  "open",
  "powered"
 ],
 "minecraft:crimson_hanging_sign": [
  "attached",
  "rotation",
  "waterlogged"
 ],
 "minecraft:crimson_hyphae": [
  "axis"
 ],
 "minecraft:crimson_pressure_plate": [
  "powered"
 ],
 "minecraft:crimson_shelf": [
  "facing",
  "powered",
  "side_chain",
  "waterlogged"
 ],
 "minecraft:crimson_sign": [
  "rotation",
  "waterlogged"
 ],
 "minecraft:crimson_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:crimson_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:crimson_stem": [
  "axis"
 ],
 "minecraft:crimson_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:crimson_wall_hanging_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:crimson_wall_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:cut_copper_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:cut_copper_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:cut_red_sandstone_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:cut_sandstone_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:cyan_banner": [
  "rotation"
 ],
 "minecraft:cyan_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:cyan_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:cyan_candle_cake": [
  "lit"
 ],
 "minecraft:cyan_glazed_terracotta": [
  "facing"
 ],
 "minecraft:cyan_shulker_box": [
  "facing"
 ],
 "minecraft:cyan_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:cyan_wall_banner": [
  "facing"
 ],
 "minecraft:damaged_anvil": [
  "facing"
 ],
 "minecraft:dark_oak_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:dark_oak_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:dark_oak_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:dark_oak_fence_gate": [
  "facing",
  "in_wall",
  "open",
  "powered"
 ],
 "minecraft:dark_oak_hanging_sign": [
  "attached",
  "rotation",
  "waterlogged"
 ],
 "minecraft:dark_oak_leaves": [
  "distance",
  "persistent",
  "waterlogged"
 ],
 "minecraft:dark_oak_log": [
  "axis"
 ],
 "minecraft:dark_oak_pressure_plate": [
  "powered"
 ],
 "minecraft:dark_oak_sapling": [
  "stage"
 ],
 "minecraft:dark_oak_shelf": [
  "facing",
  "powered",
  "side_chain",
  "waterlogged"
 ],
 "minecraft:dark_oak_sign": [
  "rotation",
  "waterlogged"
 ],
 "minecraft:dark_oak_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:dark_oak_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:dark_oak_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:dark_oak_wall_hanging_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:dark_oak_wall_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:dark_oak_wood": [
  "axis"
 ],
 "minecraft:dark_prismarine_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:dark_prismarine_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:daylight_detector": [
  "inverted",
  "power"
 ],
 "minecraft:dead_brain_coral": [
  "waterlogged"
 ],
 "minecraft:dead_brain_coral_fan": [
  "waterlogged"
 ],
 "minecraft:dead_brain_coral_wall_fan": [
  "facing",
  "waterlogged"
 ],
 "minecraft:dead_bubble_coral": [
  "waterlogged"
 ],
 "minecraft:dead_bubble_coral_fan": [
  "waterlogged"
 ],
 "minecraft:dead_bubble_coral_wall_fan": [
  "facing",
  "waterlogged"
 ],
 "minecraft:dead_fire_coral": [
  "waterlogged"
 ],
 "minecraft:dead_fire_coral_fan": [
  "waterlogged"
 ],
 "minecraft:dead_fire_coral_wall_fan": [
  "facing",
  "waterlogged"
 ],
 "minecraft:dead_horn_coral": [
  "waterlogged"
 ],
 "minecraft:dead_horn_coral_fan": [
  "waterlogged"
 ],
 "minecraft:dead_horn_coral_wall_fan": [
  "facing",
  "waterlogged"
 ],
 "minecraft:dead_tube_coral": [
  "waterlogged"
 ],
 "minecraft:dead_tube_coral_fan": [
  "waterlogged"
 ],
 "minecraft:dead_tube_coral_wall_fan": [
  "facing",
  "waterlogged"
 ],
 "minecraft:decorated_pot": [
  "cracked",
  "facing",
  "waterlogged"
 ],
 "minecraft:deepslate": [
  "axis"
 ],
 "minecraft:deepslate_brick_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:deepslate_brick_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:deepslate_brick_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:deepslate_redstone_ore": [
  "lit"
 ],
 "minecraft:deepslate_tile_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:deepslate_tile_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:deepslate_tile_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:detector_rail": [
  "powered",
  "shape",
  "waterlogged"
 ],
 "minecraft:diorite_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:diorite_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:diorite_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:dispenser": [
  "facing",
  "triggered"
 ],
 "minecraft:dragon_head": [
  "powered",
  "rotation"
 ],
 "minecraft:dragon_wall_head": [
  "facing",
  "powered"
 ],
 "minecraft:dried_ghast": [
  "facing",
  "hydration",
  "waterlogged"
 ],
 "minecraft:dropper": [
  "facing",
  "triggered"
 ],
 "minecraft:end_portal_frame": [
  "eye",
  "facing"
 ],
 "minecraft:end_rod": [
  "facing"
 ],
 "minecraft:end_stone_brick_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:end_stone_brick_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:end_stone_brick_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:ender_chest": [
  "facing",
  "waterlogged"
 ],
 "minecraft:exposed_copper_bars": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:exposed_copper_bulb": [
  "lit",
  "powered"
 ],
 "minecraft:exposed_copper_chain": [
  "axis",
  "waterlogged"
 ],
 "minecraft:exposed_copper_chest": [
  "facing",
  "type",
  "waterlogged"
 ],
 "minecraft:exposed_copper_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:exposed_copper_golem_statue": [
  "copper_golem_pose",
  "facing",
  "waterlogged"
 ],
 "minecraft:exposed_copper_grate": [
  "waterlogged"
 ],
 "minecraft:exposed_copper_lantern": [
  "hanging",
  "waterlogged"
 ],
 "minecraft:exposed_copper_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:exposed_cut_copper_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:exposed_cut_copper_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:exposed_lightning_rod": [
  "facing",
  "powered",
  "waterlogged"
 ],
 "minecraft:farmland": [
  "moisture"
 ],
 "minecraft:fire": [
  "age",
  "east",
  "north",
  "south",
  "up",
  "west"
 ],
 "minecraft:fire_coral": [
  "waterlogged"
 ],
 "minecraft:fire_coral_fan": [
  "waterlogged"
 ],
 "minecraft:fire_coral_wall_fan": [
  "facing",
  "waterlogged"
 ],
 "minecraft:flowering_azalea_leaves": [
  "distance",
  "persistent",
  "waterlogged"
 ],
 "minecraft:frosted_ice": [
  "age"
 ],
 "minecraft:furnace": [
  "facing",
  "lit"
 ],
 "minecraft:glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:glow_lichen": [
  "down",
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:granite_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:granite_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:granite_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:grass_block": [
  "snowy"
 ],
 "minecraft:gray_banner": [
  "rotation"
 ],
 "minecraft:gray_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:gray_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:gray_candle_cake": [
  "lit"
 ],
 "minecraft:gray_glazed_terracotta": [
  "facing"
 ],
 "minecraft:gray_shulker_box": [
  "facing"
 ],
 "minecraft:gray_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:gray_wall_banner": [
  "facing"
 ],
 "minecraft:green_banner": [
  "rotation"
 ],
 "minecraft:green_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:green_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:green_candle_cake": [
  "lit"
 ],
 "minecraft:green_glazed_terracotta": [
  "facing"
 ],
 "minecraft:green_shulker_box": [
  "facing"
 ],
 "minecraft:green_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:green_wall_banner": [
  "facing"
 ],
 "minecraft:grindstone": [
  "face",
  "facing"
 ],
 "minecraft:hanging_roots": [
  "waterlogged"
 ],
 "minecraft:hay_block": [
  "axis"
 ],
 "minecraft:heavy_core": [
  "waterlogged"
 ],
 "minecraft:heavy_weighted_pressure_plate": [
  "power"
 ],
 "minecraft:hopper": [
  "enabled",
  "facing"
 ],
 "minecraft:horn_coral": [
  "waterlogged"
 ],
 "minecraft:horn_coral_fan": [
  "waterlogged"
 ],
 "minecraft:horn_coral_wall_fan": [
  "facing",
  "waterlogged"
 ],
 "minecraft:infested_deepslate": [
  "axis"
 ],
 "minecraft:iron_bars": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:iron_chain": [
  "axis",
  "waterlogged"
 ],
 "minecraft:iron_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:iron_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:jack_o_lantern": [
  "facing"
 ],
 "minecraft:jigsaw": [
  "orientation"
 ],
 "minecraft:jukebox": [
  "has_record"
 ],
 "minecraft:jungle_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:jungle_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:jungle_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:jungle_fence_gate": [
  "facing",
  "in_wall",
  "open",
  "powered"
 ],
 "minecraft:jungle_hanging_sign": [
  "attached",
  "rotation",
  "waterlogged"
 ],
 "minecraft:jungle_leaves": [
  "distance",
  "persistent",
  "waterlogged"
 ],
 "minecraft:jungle_log": [
  "axis"
 ],
 "minecraft:jungle_pressure_plate": [
  "powered"
 ],
 "minecraft:jungle_sapling": [
  "stage"
 ],
 "minecraft:jungle_shelf": [
  "facing",
  "powered",
  "side_chain",
  "waterlogged"
 ],
 "minecraft:jungle_sign": [
  "rotation",
  "waterlogged"
 ],
 "minecraft:jungle_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:jungle_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:jungle_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:jungle_wall_hanging_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:jungle_wall_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:jungle_wood": [
  "axis"
 ],
 "minecraft:kelp": [
  "age"
 ],
 "minecraft:ladder": [
  "facing",
  "waterlogged"
 ],
 "minecraft:lantern": [
  "hanging",
  "waterlogged"
 ],
 "minecraft:large_amethyst_bud": [
  "facing",
  "waterlogged"
 ],
 "minecraft:large_fern": [
  "half"
 ],
 "minecraft:lava": [
  "level"
 ],
 "minecraft:leaf_litter": [
  "facing",
  "segment_amount"
 ],
 "minecraft:lectern": [
  "facing",
  "has_book",
  "powered"
 ],
 "minecraft:lever": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:light": [
  "level",
  "waterlogged"
 ],
 "minecraft:light_blue_banner": [
  "rotation"
 ],
 "minecraft:light_blue_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:light_blue_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:light_blue_candle_cake": [
  "lit"
 ],
 "minecraft:light_blue_glazed_terracotta": [
  "facing"
 ],
 "minecraft:light_blue_shulker_box": [
  "facing"
 ],
 "minecraft:light_blue_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:light_blue_wall_banner": [
  "facing"
 ],
 "minecraft:light_gray_banner": [
  "rotation"
 ],
 "minecraft:light_gray_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:light_gray_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:light_gray_candle_cake": [
  "lit"
 ],
 "minecraft:light_gray_glazed_terracotta": [
  "facing"
 ],
 "minecraft:light_gray_shulker_box": [
  "facing"
 ],
 "minecraft:light_gray_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:light_gray_wall_banner": [
  "facing"
 ],
 "minecraft:light_weighted_pressure_plate": [
  "power"
 ],
 "minecraft:lightning_rod": [
  "facing",
  "powered",
  "waterlogged"
 ],
 "minecraft:lilac": [
  "half"
 ],
 "minecraft:lime_banner": [
  "rotation"
 ],
 "minecraft:lime_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:lime_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:lime_candle_cake": [
  "lit"
 ],
 "minecraft:lime_glazed_terracotta": [
  "facing"
 ],
 "minecraft:lime_shulker_box": [
  "facing"
 ],
 "minecraft:lime_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:lime_wall_banner": [
  "facing"
 ],
 "minecraft:loom": [
  "facing"
 ],
 "minecraft:magenta_banner": [
  "rotation"
 ],
 "minecraft:magenta_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:magenta_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:magenta_candle_cake": [
  "lit"
 ],
 "minecraft:magenta_glazed_terracotta": [
  "facing"
 ],
 "minecraft:magenta_shulker_box": [
  "facing"
 ],
 "minecraft:magenta_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:magenta_wall_banner": [
  "facing"
 ],
 "minecraft:mangrove_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:mangrove_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:mangrove_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:mangrove_fence_gate": [
  "facing",
  "in_wall",
  "open",
  "powered"
 ],
 "minecraft:mangrove_hanging_sign": [
  "attached",
  "rotation",
  "waterlogged"
 ],
 "minecraft:mangrove_leaves": [
  "distance",
  "persistent",
  "waterlogged"
 ],
 "minecraft:mangrove_log": [
  "axis"
 ],
 "minecraft:mangrove_pressure_plate": [
  "powered"
 ],
 "minecraft:mangrove_propagule": [
  "age",
  "hanging",
  "stage",
  "waterlogged"
 ],
 "minecraft:mangrove_roots": [
  "waterlogged"
 ],
 "minecraft:mangrove_shelf": [
  "facing",
  "powered",
  "side_chain",
  "waterlogged"
 ],
 "minecraft:mangrove_sign": [
  "rotation",
  "waterlogged"
 ],
 "minecraft:mangrove_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:mangrove_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:mangrove_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:mangrove_wall_hanging_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:mangrove_wall_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:mangrove_wood": [
  "axis"
 ],
 "minecraft:medium_amethyst_bud": [
  "facing",
  "waterlogged"
 ],
 "minecraft:melon_stem": [
  "age"
 ],
 "minecraft:mossy_cobblestone_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:mossy_cobblestone_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:mossy_cobblestone_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:mossy_stone_brick_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:mossy_stone_brick_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:mossy_stone_brick_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:moving_piston": [
  "facing",
  "type"
 ],
 "minecraft:mud_brick_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:mud_brick_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:mud_brick_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:muddy_mangrove_roots": [
  "axis"
 ],
 "minecraft:mushroom_stem": [
  "down",
  "east",
  "north",
  "south",
  "up",
  "west"
 ],
 "minecraft:mycelium": [
  "snowy"
 ],
 "minecraft:nether_brick_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:nether_brick_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:nether_brick_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:nether_brick_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:nether_portal": [
  "axis"
 ],
 "minecraft:nether_wart": [
  "age"
 ],
 "minecraft:note_block": [
  "instrument",
  "note",
  "powered"
 ],
 "minecraft:oak_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:oak_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:oak_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:oak_fence_gate": [
  "facing",
  "in_wall",
  "open",
  "powered"
 ],
 "minecraft:oak_hanging_sign": [
  "attached",
  "rotation",
  "waterlogged"
 ],
 "minecraft:oak_leaves": [
  "distance",
  "persistent",
  "waterlogged"
 ],
 "minecraft:oak_log": [
  "axis"
 ],
 "minecraft:oak_pressure_plate": [
  "powered"
 ],
 "minecraft:oak_sapling": [
  "stage"
 ],
 "minecraft:oak_shelf": [
  "facing",
  "powered",
  "side_chain",
  "waterlogged"
 ],
 "minecraft:oak_sign": [
  "rotation",
  "waterlogged"
 ],
 "minecraft:oak_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:oak_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:oak_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:oak_wall_hanging_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:oak_wall_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:oak_wood": [
  "axis"
 ],
 "minecraft:observer": [
  "facing",
  "powered"
 ],
 "minecraft:ochre_froglight": [
  "axis"
 ],
 "minecraft:orange_banner": [
  "rotation"
 ],
 "minecraft:orange_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:orange_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:orange_candle_cake": [
  "lit"
 ],
 "minecraft:orange_glazed_terracotta": [
  "facing"
 ],
 "minecraft:orange_shulker_box": [
  "facing"
 ],
 "minecraft:orange_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:orange_wall_banner": [
  "facing"
 ],
 "minecraft:oxidized_copper_bars": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:oxidized_copper_bulb": [
  "lit",
  "powered"
 ],
 "minecraft:oxidized_copper_chain": [
  "axis",
  "waterlogged"
 ],
 "minecraft:oxidized_copper_chest": [
  "facing",
  "type",
  "waterlogged"
 ],
 "minecraft:oxidized_copper_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:oxidized_copper_golem_statue": [
  "copper_golem_pose",
  "facing",
  "waterlogged"
 ],
 "minecraft:oxidized_copper_grate": [
  "waterlogged"
 ],
 "minecraft:oxidized_copper_lantern": [
  "hanging",
  "waterlogged"
 ],
 "minecraft:oxidized_copper_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:oxidized_cut_copper_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:oxidized_cut_copper_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:oxidized_lightning_rod": [
  "facing",
  "powered",
  "waterlogged"
 ],
 "minecraft:pale_hanging_moss": [
  "tip"
 ],
 "minecraft:pale_moss_carpet": [
  "bottom",
  "east",
  "north",
  "south",
  "west"
 ],
 "minecraft:pale_oak_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:pale_oak_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:pale_oak_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:pale_oak_fence_gate": [
  "facing",
  "in_wall",
  "open",
  "powered"
 ],
 "minecraft:pale_oak_hanging_sign": [
  "attached",
  "rotation",
  "waterlogged"
 ],
 "minecraft:pale_oak_leaves": [
  "distance",
  "persistent",
  "waterlogged"
 ],
 "minecraft:pale_oak_log": [
  "axis"
 ],
 "minecraft:pale_oak_pressure_plate": [
  "powered"
 ],
 "minecraft:pale_oak_sapling": [
  "stage"
 ],
 "minecraft:pale_oak_shelf": [
  "facing",
  "powered",
  "side_chain",
  "waterlogged"
 ],
 "minecraft:pale_oak_sign": [
  "rotation",
  "waterlogged"
 ],
 "minecraft:pale_oak_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:pale_oak_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:pale_oak_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:pale_oak_wall_hanging_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:pale_oak_wall_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:pale_oak_wood": [
  "axis"
 ],
 "minecraft:pearlescent_froglight": [
  "axis"
 ],
 "minecraft:peony": [
  "half"
 ],
 "minecraft:petrified_oak_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:piglin_head": [
  "powered",
  "rotation"
 ],
 "minecraft:piglin_wall_head": [
  "facing",
  "powered"
 ],
 "minecraft:pink_banner": [
  "rotation"
 ],
 "minecraft:pink_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:pink_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:pink_candle_cake": [
  "lit"
 ],
 "minecraft:pink_glazed_terracotta": [
  "facing"
 ],
 "minecraft:pink_petals": [
  "facing",
  "flower_amount"
 ],
 "minecraft:pink_shulker_box": [
  "facing"
 ],
 "minecraft:pink_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:pink_wall_banner": [
  "facing"
 ],
 "minecraft:piston": [
  "extended",
  "facing"
 ],
 "minecraft:piston_head": [
  "facing",
  "short",
  "type"
 ],
 "minecraft:pitcher_crop": [
  "age",
  "half"
 ],
 "minecraft:pitcher_plant": [
  "half"
 ],
 "minecraft:player_head": [
  "powered",
  "rotation"
 ],
 "minecraft:player_wall_head": [
  "facing",
  "powered"
 ],
 "minecraft:podzol": [
  "snowy"
 ],
 "minecraft:pointed_dripstone": [
  "thickness",
  "vertical_direction",
  "waterlogged"
 ],
 "minecraft:polished_andesite_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:polished_andesite_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:polished_basalt": [
  "axis"
 ],
 "minecraft:polished_blackstone_brick_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:polished_blackstone_brick_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:polished_blackstone_brick_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:polished_blackstone_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:polished_blackstone_pressure_plate": [
  "powered"
 ],
 "minecraft:polished_blackstone_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:polished_blackstone_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:polished_blackstone_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:polished_deepslate_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:polished_deepslate_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:polished_deepslate_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:polished_diorite_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:polished_diorite_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:polished_granite_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:polished_granite_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:polished_tuff_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:polished_tuff_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:polished_tuff_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:potatoes": [
  "age"
 ],
 "minecraft:powder_snow_cauldron": [
  "level"
 ],
 "minecraft:powered_rail": [
  "powered",
  "shape",
  "waterlogged"
 ],
 "minecraft:prismarine_brick_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:prismarine_brick_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:prismarine_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:prismarine_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:prismarine_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:pumpkin_stem": [
  "age"
 ],
 "minecraft:purple_banner": [
  "rotation"
 ],
 "minecraft:purple_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:purple_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:purple_candle_cake": [
  "lit"
 ],
 "minecraft:purple_glazed_terracotta": [
  "facing"
 ],
 "minecraft:purple_shulker_box": [
  "facing"
 ],
 "minecraft:purple_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:purple_wall_banner": [
  "facing"
 ],
 "minecraft:purpur_pillar": [
  "axis"
 ],
 "minecraft:purpur_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:purpur_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:quartz_pillar": [
  "axis"
 ],
 "minecraft:quartz_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:quartz_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:rail": [
  "shape",
  "waterlogged"
 ],
 "minecraft:red_banner": [
  "rotation"
 ],
 "minecraft:red_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:red_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:red_candle_cake": [
  "lit"
 ],
 "minecraft:red_glazed_terracotta": [
  "facing"
 ],
 "minecraft:red_mushroom_block": [
  "down",
  "east",
  "north",
  "south",
  "up",
  "west"
 ],
 "minecraft:red_nether_brick_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:red_nether_brick_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:red_nether_brick_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:red_sandstone_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:red_sandstone_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:red_sandstone_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:red_shulker_box": [
  "facing"
 ],
 "minecraft:red_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:red_wall_banner": [
  "facing"
 ],
 "minecraft:redstone_lamp": [
  "lit"
 ],
 "minecraft:redstone_ore": [
  "lit"
 ],
 "minecraft:redstone_torch": [
  "lit"
 ],
 "minecraft:redstone_wall_torch": [
  "facing",
  "lit"
 ],
 "minecraft:redstone_wire": [
  "east",
  "north",
  "power",
  "south",
  "west"
 ],
 "minecraft:repeater": [
  "delay",
  "facing",
  "locked",
  "powered"
 ],
 "minecraft:repeating_command_block": [
  "conditional",
  "facing"
 ],
 "minecraft:resin_brick_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:resin_brick_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:resin_brick_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:resin_clump": [
  "down",
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:respawn_anchor": [
  "charges"
 ],
 "minecraft:rose_bush": [
  "half"
 ],
 "minecraft:sandstone_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:sandstone_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:sandstone_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:scaffolding": [
  "bottom",
  "distance",
  "waterlogged"
 ],
 "minecraft:sculk_catalyst": [
  "bloom"
 ],
 "minecraft:sculk_sensor": [
  "power",
  "sculk_sensor_phase",
  "waterlogged"
 ],
 "minecraft:sculk_shrieker": [
  "can_summon",
  "shrieking",
  "waterlogged"
 ],
 "minecraft:sculk_vein": [
  "down",
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:sea_pickle": [
  "pickles",
  "waterlogged"
 ],
 "minecraft:shulker_box": [
  "facing"
 ],
 "minecraft:skeleton_skull": [
  "powered",
  "rotation"
 ],
 "minecraft:skeleton_wall_skull": [
  "facing",
  "powered"
 ],
 "minecraft:small_amethyst_bud": [
  "facing",
  "waterlogged"
 ],
 "minecraft:small_dripleaf": [
  "facing",
  "half",
  "waterlogged"
 ],
 "minecraft:smoker": [
  "facing",
  "lit"
 ],
 "minecraft:smooth_quartz_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:smooth_quartz_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:smooth_red_sandstone_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:smooth_red_sandstone_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:smooth_sandstone_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:smooth_sandstone_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:smooth_stone_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:sniffer_egg": [
  "hatch"
 ],
 "minecraft:snow": [
  "layers"
 ],
 "minecraft:soul_campfire": [
  "facing",
  "lit",
  "signal_fire",
  "waterlogged"
 ],
 "minecraft:soul_lantern": [
  "hanging",
  "waterlogged"
 ],
 "minecraft:soul_wall_torch": [
  "facing"
 ],
 "minecraft:spruce_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:spruce_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:spruce_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:spruce_fence_gate": [
  "facing",
  "in_wall",
  "open",
  "powered"
 ],
 "minecraft:spruce_hanging_sign": [
  "attached",
  "rotation",
  "waterlogged"
 ],
 "minecraft:spruce_leaves": [
  "distance",
  "persistent",
  "waterlogged"
 ],
 "minecraft:spruce_log": [
  "axis"
 ],
 "minecraft:spruce_pressure_plate": [
  "powered"
 ],
 "minecraft:spruce_sapling": [
  "stage"
 ],
 "minecraft:spruce_shelf": [
  "facing",
  "powered",
  "side_chain",
  "waterlogged"
 ],
 "minecraft:spruce_sign": [
  "rotation",
  "waterlogged"
 ],
 "minecraft:spruce_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:spruce_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:spruce_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:spruce_wall_hanging_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:spruce_wall_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:spruce_wood": [
  "axis"
 ],
 "minecraft:sticky_piston": [
  "extended",
  "facing"
 ],
 "minecraft:stone_brick_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:stone_brick_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:stone_brick_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:stone_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:stone_pressure_plate": [
  "powered"
 ],
 "minecraft:stone_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:stone_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:stonecutter": [
  "facing"
 ],
 "minecraft:stripped_acacia_log": [
  "axis"
 ],
 "minecraft:stripped_acacia_wood": [
  "axis"
 ],
 "minecraft:stripped_bamboo_block": [
  "axis"
 ],
 "minecraft:stripped_birch_log": [
  "axis"
 ],
 "minecraft:stripped_birch_wood": [
  "axis"
 ],
 "minecraft:stripped_cherry_log": [
  "axis"
 ],
 "minecraft:stripped_cherry_wood": [
  "axis"
 ],
 "minecraft:stripped_crimson_hyphae": [
  "axis"
 ],
 "minecraft:stripped_crimson_stem": [
  "axis"
 ],
 "minecraft:stripped_dark_oak_log": [
  "axis"
 ],
 "minecraft:stripped_dark_oak_wood": [
  "axis"
 ],
 "minecraft:stripped_jungle_log": [
  "axis"
 ],
 "minecraft:stripped_jungle_wood": [
  "axis"
 ],
 "minecraft:stripped_mangrove_log": [
  "axis"
 ],
 "minecraft:stripped_mangrove_wood": [
  "axis"
 ],
 "minecraft:stripped_oak_log": [
  "axis"
 ],
 "minecraft:stripped_oak_wood": [
  "axis"
 ],
 "minecraft:stripped_pale_oak_log": [
  "axis"
 ],
 "minecraft:stripped_pale_oak_wood": [
  "axis"
 ],
 "minecraft:stripped_spruce_log": [
  "axis"
 ],
 "minecraft:stripped_spruce_wood": [
  "axis"
 ],
 "minecraft:stripped_warped_hyphae": [
  "axis"
 ],
 "minecraft:stripped_warped_stem": [
  "axis"
 ],
 "minecraft:structure_block": [
  "mode"
 ],
 "minecraft:sugar_cane": [
  "age"
 ],
 "minecraft:sunflower": [
  "half"
 ],
 "minecraft:suspicious_gravel": [
  "dusted"
 ],
 "minecraft:suspicious_sand": [
  "dusted"
 ],
 "minecraft:sweet_berry_bush": [
  "age"
 ],
 "minecraft:tall_grass": [
  "half"
 ],
 "minecraft:tall_seagrass": [
  "half"
 ],
 "minecraft:target": [
  "power"
 ],
 "minecraft:test_block": [
  "mode"
 ],
 "minecraft:tnt": [
  "unstable"
 ],
 "minecraft:torchflower_crop": [
  "age"
 ],
 "minecraft:trapped_chest": [
  "facing",
  "type",
  "waterlogged"
 ],
 "minecraft:trial_spawner": [
  "ominous",
  "trial_spawner_state"
 ],
 "minecraft:tripwire": [
  "attached",
  "disarmed",
  "east",
  "north",
  "powered",
  "south",
  "west"
 ],
 "minecraft:tripwire_hook": [
  "attached",
  "facing",
  "powered"
 ],
 "minecraft:tube_coral": [
  "waterlogged"
 ],
 "minecraft:tube_coral_fan": [
  "waterlogged"
 ],
 "minecraft:tube_coral_wall_fan": [
  "facing",
  "waterlogged"
 ],
 "minecraft:tuff_brick_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:tuff_brick_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:tuff_brick_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:tuff_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:tuff_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:tuff_wall": [
  "east",
  "north",
  "south",
  "up",
  "waterlogged",
  "west"
 ],
 "minecraft:turtle_egg": [
  "eggs",
  "hatch"
 ],
 "minecraft:twisting_vines": [
  "age"
 ],
 "minecraft:vault": [
  "facing",
  "ominous",
  "vault_state"
 ],
 "minecraft:verdant_froglight": [
  "axis"
 ],
 "minecraft:vine": [
  "east",
  "north",
  "south",
  "up",
  "west"
 ],
 "minecraft:wall_torch": [
  "facing"
 ],
 "minecraft:warped_button": [
  "face",
  "facing",
  "powered"
 ],
 "minecraft:warped_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:warped_fence": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:warped_fence_gate": [
  "facing",
  "in_wall",
  "open",
  "powered"
 ],
 "minecraft:warped_hanging_sign": [
  "attached",
  "rotation",
  "waterlogged"
 ],
 "minecraft:warped_hyphae": [
  "axis"
 ],
 "minecraft:warped_pressure_plate": [
  "powered"
 ],
 "minecraft:warped_shelf": [
  "facing",
  "powered",
  "side_chain",
  "waterlogged"
 ],
 "minecraft:warped_sign": [
  "rotation",
  "waterlogged"
 ],
 "minecraft:warped_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:warped_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:warped_stem": [
  "axis"
 ],
 "minecraft:warped_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:warped_wall_hanging_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:warped_wall_sign": [
  "facing",
  "waterlogged"
 ],
 "minecraft:water": [
  "level"
 ],
 "minecraft:water_cauldron": [
  "level"
 ],
 "minecraft:waxed_copper_bars": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:waxed_copper_bulb": [
  "lit",
  "powered"
 ],
 "minecraft:waxed_copper_chain": [
  "axis",
  "waterlogged"
 ],
 "minecraft:waxed_copper_chest": [
  "facing",
  "type",
  "waterlogged"
 ],
 "minecraft:waxed_copper_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:waxed_copper_golem_statue": [
  "copper_golem_pose",
  "facing",
  "waterlogged"
 ],
 "minecraft:waxed_copper_grate": [
  "waterlogged"
 ],
 "minecraft:waxed_copper_lantern": [
  "hanging",
  "waterlogged"
 ],
 "minecraft:waxed_copper_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:waxed_cut_copper_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:waxed_cut_copper_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:waxed_exposed_copper_bars": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:waxed_exposed_copper_bulb": [
  "lit",
  "powered"
 ],
 "minecraft:waxed_exposed_copper_chain": [
  "axis",
  "waterlogged"
 ],
 "minecraft:waxed_exposed_copper_chest": [
  "facing",
  "type",
  "waterlogged"
 ],
 "minecraft:waxed_exposed_copper_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:waxed_exposed_copper_golem_statue": [
  "copper_golem_pose",
  "facing",
  "waterlogged"
 ],
 "minecraft:waxed_exposed_copper_grate": [
  "waterlogged"
 ],
 "minecraft:waxed_exposed_copper_lantern": [
  "hanging",
  "waterlogged"
 ],
 "minecraft:waxed_exposed_copper_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:waxed_exposed_cut_copper_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:waxed_exposed_cut_copper_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:waxed_exposed_lightning_rod": [
  "facing",
  "powered",
  "waterlogged"
 ],
 "minecraft:waxed_lightning_rod": [
  "facing",
  "powered",
  "waterlogged"
 ],
 "minecraft:waxed_oxidized_copper_bars": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:waxed_oxidized_copper_bulb": [
  "lit",
  "powered"
 ],
 "minecraft:waxed_oxidized_copper_chain": [
  "axis",
  "waterlogged"
 ],
 "minecraft:waxed_oxidized_copper_chest": [
  "facing",
  "type",
  "waterlogged"
 ],
 "minecraft:waxed_oxidized_copper_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:waxed_oxidized_copper_golem_statue": [
  "copper_golem_pose",
  "facing",
  "waterlogged"
 ],
 "minecraft:waxed_oxidized_copper_grate": [
  "waterlogged"
 ],
 "minecraft:waxed_oxidized_copper_lantern": [
  "hanging",
  "waterlogged"
 ],
 "minecraft:waxed_oxidized_copper_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:waxed_oxidized_cut_copper_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:waxed_oxidized_cut_copper_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:waxed_oxidized_lightning_rod": [
  "facing",
  "powered",
  "waterlogged"
 ],
 "minecraft:waxed_weathered_copper_bars": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:waxed_weathered_copper_bulb": [
  "lit",
  "powered"
 ],
 "minecraft:waxed_weathered_copper_chain": [
  "axis",
  "waterlogged"
 ],
 "minecraft:waxed_weathered_copper_chest": [
  "facing",
  "type",
  "waterlogged"
 ],
 "minecraft:waxed_weathered_copper_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:waxed_weathered_copper_golem_statue": [
  "copper_golem_pose",
  "facing",
  "waterlogged"
 ],
 "minecraft:waxed_weathered_copper_grate": [
  "waterlogged"
 ],
 "minecraft:waxed_weathered_copper_lantern": [
  "hanging",
  "waterlogged"
 ],
 "minecraft:waxed_weathered_copper_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:waxed_weathered_cut_copper_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:waxed_weathered_cut_copper_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:waxed_weathered_lightning_rod": [
  "facing",
  "powered",
  "waterlogged"
 ],
 "minecraft:weathered_copper_bars": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:weathered_copper_bulb": [
  "lit",
  "powered"
 ],
 "minecraft:weathered_copper_chain": [
  "axis",
  "waterlogged"
 ],
 "minecraft:weathered_copper_chest": [
  "facing",
  "type",
  "waterlogged"
 ],
 "minecraft:weathered_copper_door": [
  "facing",
  "half",
  "hinge",
  "open",
  "powered"
 ],
 "minecraft:weathered_copper_golem_statue": [
  "copper_golem_pose",
  "facing",
  "waterlogged"
 ],
 "minecraft:weathered_copper_grate": [
  "waterlogged"
 ],
 "minecraft:weathered_copper_lantern": [
  "hanging",
  "waterlogged"
 ],
 "minecraft:weathered_copper_trapdoor": [
  "facing",
  "half",
  "open",
  "powered",
  "waterlogged"
 ],
 "minecraft:weathered_cut_copper_slab": [
  "type",
  "waterlogged"
 ],
 "minecraft:weathered_cut_copper_stairs": [
  "facing",
  "half",
  "shape",
  "waterlogged"
 ],
 "minecraft:weathered_lightning_rod": [
  "facing",
  "powered",
  "waterlogged"
 ],
 "minecraft:weeping_vines": [
  "age"
 ],
 "minecraft:wheat": [
  "age"
 ],
 "minecraft:white_banner": [
  "rotation"
 ],
 "minecraft:white_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:white_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:white_candle_cake": [
  "lit"
 ],
 "minecraft:white_glazed_terracotta": [
  "facing"
 ],
 "minecraft:white_shulker_box": [
  "facing"
 ],
 "minecraft:white_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:white_wall_banner": [
  "facing"
 ],
 "minecraft:wildflowers": [
  "facing",
  "flower_amount"
 ],
 "minecraft:wither_skeleton_skull": [
  "powered",
  "rotation"
 ],
 "minecraft:wither_skeleton_wall_skull": [
  "facing",
  "powered"
 ],
 "minecraft:yellow_banner": [
  "rotation"
 ],
 "minecraft:yellow_bed": [
  "facing",
  "occupied",
  "part"
 ],
 "minecraft:yellow_candle": [
  "candles",
  "lit",
  "waterlogged"
 ],
 "minecraft:yellow_candle_cake": [
  "lit"
 ],
 "minecraft:yellow_glazed_terracotta": [
  "facing"
 ],
 "minecraft:yellow_shulker_box": [
  "facing"
 ],
 "minecraft:yellow_stained_glass_pane": [
  "east",
  "north",
  "south",
  "waterlogged",
  "west"
 ],
 "minecraft:yellow_wall_banner": [
  "facing"
 ],
 "minecraft:zombie_head": [
  "powered",
  "rotation"
 ],
 "minecraft:zombie_wall_head": [
  "facing",
  "powered"
 ]
}"##;

static BLOCK_STATE_PROPERTIES: LazyLock<HashMap<String, Vec<String>>> = LazyLock::new(|| {
    serde_json::from_str::<HashMap<String, Vec<String>>>(BLOCK_STATE_PROPERTIES_JSON).expect("embedded data must parse")
});

/// Property names accepted by a concrete block predicate, if known.
pub fn block_state_properties(block_id: &str) -> Option<&'static [String]> {
    BLOCK_STATE_PROPERTIES.get(block_id).map(Vec::as_slice)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_block_properties() {
        let props = block_state_properties("minecraft:acacia_button").unwrap();
        assert!(props.contains(&"face".to_string()));
        assert!(props.contains(&"powered".to_string()));
        assert!(block_state_properties("minecraft:nope").is_none());
    }
}
