//! Official Minecraft 1.21.11 items report: consumable component defaults.
//!
//! Generated by work/gen-data.mts from legacy/src/minecraft-consumables-1.21.11.ts.
//! Do not edit by hand; re-run the generator after data changes.

use std::collections::{HashMap, HashSet};
use std::sync::LazyLock;

use serde_json::Value;

use crate::json::JsonObject;


static CONSUMABLE_COMPONENTS_JSON: &str = r##"{
 "minecraft:apple": {},
 "minecraft:baked_potato": {},
 "minecraft:beef": {},
 "minecraft:beetroot": {},
 "minecraft:beetroot_soup": {},
 "minecraft:bread": {},
 "minecraft:carrot": {},
 "minecraft:chicken": {
  "on_consume_effects": [
   {
    "type": "minecraft:apply_effects",
    "effects": [
     {
      "duration": 600,
      "id": "minecraft:hunger",
      "show_icon": true
     }
    ],
    "probability": 0.3
   }
  ]
 },
 "minecraft:chorus_fruit": {
  "on_consume_effects": [
   {
    "type": "minecraft:teleport_randomly"
   }
  ]
 },
 "minecraft:cod": {},
 "minecraft:cooked_beef": {},
 "minecraft:cooked_chicken": {},
 "minecraft:cooked_cod": {},
 "minecraft:cooked_mutton": {},
 "minecraft:cooked_porkchop": {},
 "minecraft:cooked_rabbit": {},
 "minecraft:cooked_salmon": {},
 "minecraft:cookie": {},
 "minecraft:dried_kelp": {
  "consume_seconds": 0.8
 },
 "minecraft:enchanted_golden_apple": {
  "on_consume_effects": [
   {
    "type": "minecraft:apply_effects",
    "effects": [
     {
      "amplifier": 1,
      "duration": 400,
      "id": "minecraft:regeneration",
      "show_icon": true
     },
     {
      "duration": 6000,
      "id": "minecraft:resistance",
      "show_icon": true
     },
     {
      "duration": 6000,
      "id": "minecraft:fire_resistance",
      "show_icon": true
     },
     {
      "amplifier": 3,
      "duration": 2400,
      "id": "minecraft:absorption",
      "show_icon": true
     }
    ]
   }
  ]
 },
 "minecraft:glow_berries": {},
 "minecraft:golden_apple": {
  "on_consume_effects": [
   {
    "type": "minecraft:apply_effects",
    "effects": [
     {
      "amplifier": 1,
      "duration": 100,
      "id": "minecraft:regeneration",
      "show_icon": true
     },
     {
      "duration": 2400,
      "id": "minecraft:absorption",
      "show_icon": true
     }
    ]
   }
  ]
 },
 "minecraft:golden_carrot": {},
 "minecraft:honey_bottle": {
  "animation": "drink",
  "consume_seconds": 2,
  "has_consume_particles": false,
  "on_consume_effects": [
   {
    "type": "minecraft:remove_effects",
    "effects": "minecraft:poison"
   }
  ],
  "sound": "minecraft:item.honey_bottle.drink"
 },
 "minecraft:melon_slice": {},
 "minecraft:milk_bucket": {
  "animation": "drink",
  "has_consume_particles": false,
  "on_consume_effects": [
   {
    "type": "minecraft:clear_all_effects"
   }
  ],
  "sound": "minecraft:entity.generic.drink"
 },
 "minecraft:mushroom_stew": {},
 "minecraft:mutton": {},
 "minecraft:ominous_bottle": {
  "animation": "drink",
  "has_consume_particles": false,
  "on_consume_effects": [
   {
    "type": "minecraft:play_sound",
    "sound": "minecraft:item.ominous_bottle.dispose"
   }
  ],
  "sound": "minecraft:entity.generic.drink"
 },
 "minecraft:poisonous_potato": {
  "on_consume_effects": [
   {
    "type": "minecraft:apply_effects",
    "effects": [
     {
      "duration": 100,
      "id": "minecraft:poison",
      "show_icon": true
     }
    ],
    "probability": 0.6
   }
  ]
 },
 "minecraft:porkchop": {},
 "minecraft:potato": {},
 "minecraft:potion": {
  "animation": "drink",
  "has_consume_particles": false,
  "sound": "minecraft:entity.generic.drink"
 },
 "minecraft:pufferfish": {
  "on_consume_effects": [
   {
    "type": "minecraft:apply_effects",
    "effects": [
     {
      "amplifier": 1,
      "duration": 1200,
      "id": "minecraft:poison",
      "show_icon": true
     },
     {
      "amplifier": 2,
      "duration": 300,
      "id": "minecraft:hunger",
      "show_icon": true
     },
     {
      "duration": 300,
      "id": "minecraft:nausea",
      "show_icon": true
     }
    ]
   }
  ]
 },
 "minecraft:pumpkin_pie": {},
 "minecraft:rabbit": {},
 "minecraft:rabbit_stew": {},
 "minecraft:rotten_flesh": {
  "on_consume_effects": [
   {
    "type": "minecraft:apply_effects",
    "effects": [
     {
      "duration": 600,
      "id": "minecraft:hunger",
      "show_icon": true
     }
    ],
    "probability": 0.8
   }
  ]
 },
 "minecraft:salmon": {},
 "minecraft:spider_eye": {
  "on_consume_effects": [
   {
    "type": "minecraft:apply_effects",
    "effects": [
     {
      "duration": 100,
      "id": "minecraft:poison",
      "show_icon": true
     }
    ]
   }
  ]
 },
 "minecraft:suspicious_stew": {},
 "minecraft:sweet_berries": {},
 "minecraft:tropical_fish": {}
}"##;

static CONSUMABLE_COMPONENTS: LazyLock<HashMap<String, JsonObject>> = LazyLock::new(|| {
    serde_json::from_str::<HashMap<String, JsonObject>>(CONSUMABLE_COMPONENTS_JSON).expect("embedded data must parse")
});

/// Base consumable component Nexo inherits for the given item, if any.
pub fn consumable_components(item_id: &str) -> Option<&'static JsonObject> {
    CONSUMABLE_COMPONENTS.get(item_id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    #[test]
    fn consumable_defaults() {
        assert!(consumable_components("minecraft:apple").unwrap().is_empty());
        let honey = consumable_components("minecraft:honey_bottle").unwrap();
        assert_eq!(honey.get("consume_seconds"), Some(&Value::from(2)));
        assert!(consumable_components("minecraft:stone").is_none());
    }
}
